/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#00464d',
        'primary-container': '#005f69',
        'on-primary': '#ffffff',
        'on-primary-container': '#8fd6e2',
        'inverse-primary': '#8bd2dd',
        'primary-fixed': '#a7eefa',
        'primary-fixed-dim': '#8bd2dd',
        secondary: '#2f6769',
        'secondary-container': '#b2eaed',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#346b6e',
        'secondary-fixed': '#b5ecef',
        'secondary-fixed-dim': '#99d0d3',
        tertiary: '#324241',
        'tertiary-container': '#485958',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#bdcfce',
        surface: '#f1fbfb',
        'surface-dim': '#d1dcdc',
        'surface-bright': '#f1fbfb',
        'surface-container': '#e5f0ef',
        'surface-container-low': '#ebf6f5',
        'surface-container-high': '#dfeaea',
        'surface-container-highest': '#dae5e4',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#dae5e4',
        'surface-tint': '#156872',
        'on-surface': '#141d1d',
        'on-surface-variant': '#3f484a',
        'inverse-surface': '#283232',
        'inverse-on-surface': '#e8f3f2',
        outline: '#6f797a',
        'outline-variant': '#bec8ca',
        background: '#f1fbfb',
        'on-background': '#141d1d',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
